name: Continuous Delivery - Deploy to AWS EC2 with CodeDeploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --production

    - name: Create deployment package
      run: |
        zip -r forumapi-${{ github.sha }}.zip . -x "*.git*" "node_modules/@types/*" "tests/*" "*.test.js" "*.md" ".github/*"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: |
        aws s3 cp forumapi-${{ github.sha }}.zip s3://${{ secrets.S3_BUCKET }}/deployments/

    - name: Deploy with CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ secrets.CODEDEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP }} \
          --s3-location bucket=${{ secrets.S3_BUCKET }},key=deployments/forumapi-${{ github.sha }}.zip,bundleType=zip \
          --description "Deployment of commit ${{ github.sha }}"