name: Continuous Integration - Run Tests and Lint

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      PGHOST: ${{ secrets.RDS_HOST}}
      PGPORT: ${{ secrets.RDS_PORT}}
      PGUSER: ${{ secrets.RDS_USERNAME}}
      PGPASSWORD: ${{ secrets.RDS_PASSWORD}}
      PGDATABASE: ${{ secrets.RDS_DATABASE}}
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PGSSLMODE: require

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run database migrations
      run: npm run migrate up

    - name: Run tests
      run: npm test

    - name: Run linter
      run: npm run lint
      continue-on-error: true
