name: CI

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      PGHOST: ${{ secrets.RDS_HOST_TEST }}
      PGPORT: ${{ secrets.RDS_PORT_TEST}}
      PGUSER: ${{ secrets.RDS_USERNAME_TEST }}
      PGPASSWORD: ${{ secrets.RDS_PASSWORD_TEST }}
      PGDATABASE: ${{ secrets.RDS_DATABASE_TEST }}
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      ACCESS_TOKEN_AGE: 3000

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run database migrations
      run: npm run migrate:test up

    - name: Run tests
      run: npm test

    - name: Run linter
      run: npm run lint
      continue-on-error: true